// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-Uz6YpeBWei27m4YTNIMEm-uLBm6JZk',
    appId: '1:641063758181:web:65b48bc025c9c5e1a2198c',
    messagingSenderId: '641063758181',
    projectId: 'tubesmobile-c4f0d',
    authDomain: 'tubesmobile-c4f0d.firebaseapp.com',
    storageBucket: 'tubesmobile-c4f0d.appspot.com',
    measurementId: 'G-Q3QHBKHJWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCrXN803EiJmGk74k-VWJF5H9_I0i4dM',
    appId: '1:641063758181:android:e3011ac2078d43cea2198c',
    messagingSenderId: '641063758181',
    projectId: 'tubesmobile-c4f0d',
    storageBucket: 'tubesmobile-c4f0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjDt_qLgFiq4bvkxr0T-U0lVGqFO2sARY',
    appId: '1:641063758181:ios:8e558d003b0b3335a2198c',
    messagingSenderId: '641063758181',
    projectId: 'tubesmobile-c4f0d',
    storageBucket: 'tubesmobile-c4f0d.appspot.com',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjDt_qLgFiq4bvkxr0T-U0lVGqFO2sARY',
    appId: '1:641063758181:ios:4a97e5162f270809a2198c',
    messagingSenderId: '641063758181',
    projectId: 'tubesmobile-c4f0d',
    storageBucket: 'tubesmobile-c4f0d.appspot.com',
    iosBundleId: 'com.example.tubes.RunnerTests',
  );
}
